name: Mod Bot

on:
  issue_comment:
    types:
      - created
      - edited

defaults:
  run:
    working-directory: src

jobs:
  bot:
    name: Run the Bot & Command

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Setup Rustup
        run: rustup toolchain install stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ./target/
          key: ${{ runner.os }}-cargo-

      - name: Install deps
        run: pnpm install

      - name: Run napi build
        run: pnpm napi build

      - name: Run bot
        run: node .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CTX: ${{ toJson(github) }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: AHQ Store Bot
          author_email: ahqsecret@gmail.com
          commit: --force
          message: Robot Action
